# Generated by Django 2.1.7 on 2019-03-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstlv1', models.CharField(max_length=20)),
                ('secondlv1', models.CharField(max_length=20)),
                ('sweet', models.CharField(max_length=30)),
                ('favcolor', models.CharField(max_length=30)),
                ('oneword', models.CharField(max_length=30)),
            ],
        ),
    ]
